### ISSUE TITLE
The Chinese name of the font needs to be called "明體" in lieu of "宋體"

### ISSUE THREAD

**Issue by ShikiSuen** [adobe-fonts/source-han-serif#1]
I know there is a common practice in mainland PRC:

` to call "宋體" as fake name "仿宋"; to call "明體" as fake name "宋體".`

However, this is not the reason to call things in wrong names. This is not academic at all.

Reference: https://www.zhihu.com/question/27360397/answer/123125103

![image](https://cloud.githubusercontent.com/assets/3164826/24639317/1f0fc23e-18ac-11e7-95c7-5cc3a51f9632.png)

**Comment by kenlunde** [comment]
For better or for worse, the Traditional Chinese name is what it is.

**Comment by zerng07** [comment]
@ShikiSuen  You don't have to clean those content. It is better to keep them for documentary.

Although it is called "思源宋體" in Traditional Chinese name, we, the people in Taiwan, use "明體" instead of "宋體" for the name. 
http://developers.googleblog.com/2017/04/noto-serif-cjk-is-here.html

**Comment by ShikiSuen** [comment]
@zerng07 keep them for what? for shame? for funny materials for LiangHai? Ridiculous.
I just nuked my mirrored repo of SHSans download on CodePlex. For anyone who having downloading issues with SHSans and SHSerif, they are gonna use BitTorrent instead from now on. None will be my bloody business. Over.

**Comment by zerng07** [comment]
That's fine if you have other concerns.

**Comment by andy0130tw** [comment]
> ..., we, the people in Taiwan, use "明體" instead of "宋體" for the name.

This seems conflicting with this,

> ... they are gonna use BitTorrent instead from now on. ...

The fact is that, in Taiwan, everyone can connect to GitHub to download the fonts easily. Even without VPNs.

By the way, I really hope that the region-specific font name for Traditional Chinese can be changed to "明體". That is the way people call fonts of that type. It is a pain to recognize a name in the font list that is not the one we used to call it.

Thanks!

**Comment by kenlunde** [comment]
I just restored the title of this issue. I will probably restore the contents, too, as I keep the email notifications. For better or worse, keeping the history is important.

If you are going to make the effort to contribute to this project, please don't nuke the contents then run away at the first sign of criticism. It makes you seem unprofessional, and I know that you are not unprofessional. All issues are open to critique, just like the project itself, hence the presence of an issue-reporting system.

**Comment by ShikiSuen** [comment]
@andy0130tw You should noticed that there is no barrier between your place (台澎金馬) and GitHub. I couldn't explain more on this topic for personal concerns.

**Comment by hfhchan** [comment]
I thought it is standard practice for font foundries operating in Taiwan abd Hong Kong to call the printing style with Kaishu strokes as 宋體 and the traditional variant as 明體, with the only exception being the loathed 新細明體.  In light of this distinction, it seems 宋體 is the correct way to go.

**Comment by zerng07** [comment]
It is not technically correct because 宋體 was firstly referred to the printing style developed in Song Dynasty which style is more like 瘦金體 and Kati. 
As the time went, the printing style became more standardized and developed its own features such as slim horizontal stokes, strong vertical strokes, and triangle terminals...etc in Ming Dynasty. People in China didn't change the term, and still called it as "宋體".
The printing style in Song Dynasty was reintroduced in Qing Dynasty, but they encountered the problem with the naming issue. The real 宋體 style in Song Dynasty was different from what the people called, so a new term "仿宋體" was created to refer this true 宋體.
It is a historical issue that people call it as 宋體 but not technically.

**Comment by zerng07** [comment]
The printing or publishing systems in Taiwan are mostly produced by Japanese when the Japan government ruling time, while some foundries buy the fonts directly from China. That's why general public (民間) mostly see the printing serif style as 明體 in Taiwan.
In the years of 國民政府, most of the officers or professionals (官方) who developed 國字宋體母稿 in Minister of Education studied in mainland China before or their mentors were from China, so they used the 宋體 as the name by nature. That is what they called and what they learned.
However, in the modern days, people directly know the terms from the operating system or office suites, and they learn this serif printing style named as 明體 from the most used 細明體 and 新細明體. It is confused by most of the people who don't know the complicated historical background.

**Comment by hfhchan** [comment]
I am aware of the intricate historical reasons for the difference in naming.  However, I only wish to point out the two largest local font foundries in Taiwan and Hong Kong, 文鼎 and 華康, consistently use the terms 宋體 and 明體 to denote the difference between 楷化-style and traditional-style respectively.

**Comment by ShikiSuen** [comment]
@hfhchan What about inviting those people from Arphic and DynaComware to come here to share their opinions by themselves instead of your deduction based on your mere observation? I think this could help us see what they really think of.

**Comment by KrasnayaPloshchad** [comment]
@hfhchan Maybe we can try to do it based on a fork of this project

**Comment by hfhchan** [comment]
@KrasnayaPloshchad my stance is the current name should remain UNCHANGED.  Regarding the implementation of traditional shapes, please open another issue if you wish.

**Comment by KrasnayaPloshchad** [comment]
@hfhchan Oh, I see, sorry.

**Comment by c933103** [comment]
Just stumbled upon this issue and is a bit out of loop regarding what the issue is about and how this issue get closed, but according to a blogpost I just read http://blog.justfont.com/2013/09/mingti_or_songti_1/ , it seems like there are historical origin to both name. Personally I am used to expect a font named Song to be from mainland China and a font named Ming to be for traditional Chinese, but that could just because I am influenced by the name of default font in MS Windows and that I am not familiar with various different font.

**Comment by zerng07** [comment]
Please see Issue #8 for the official response.

**Comment by c933103** [comment]
so what ShikiSuen saying is not about how people in some region favor one name over another, instead it is about how the traditional usage of the name Song is wrong and thus the name shall be changed to Ming regardless of region and that because people here are not renaming the font due to this, ShikiSuen is going to pull his mirror for the font to make it harder for mainland Chinese users to download this font. ?

**Comment by ShikiSuen** [comment]
@c933103 You messed up one thing: I was expecting a download mirror within Mainland PRC for those people who have difficulties downloading things from GitHub.

Regarding what a really 宋體 fontstyle is, it is absolutely not the one emerged since Ming dynasty. Do history research of font style development prior to make assumptions.
