### ISSUE TITLE
Support OpenType Font Variation

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [adobe-fonts/source-han-serif#16]
OpenType specification introduced font variation in 1.8, as _[Type is Beautiful](http://www.typeisbeautiful.com/2016/09/10968/zh-hant/)_, this technology has following advantages for CJK typefaces: it’s easy to adjust the gray scale, proportion, alignments with Western scripts, easy to implement multiple font weight and style within single font file, save unwhispered expenses for meticulous and global hinting and so on. If Source Han Serif adapt this technology, it would get better quality visual appearences.

**Comment by kenlunde** [comment]
[Baby steps](https://www.youtube.com/watch?v=Yl6s6DGapug). Seriously. Because a non-zero amount of effort is required to develop a Variable Font.

In brighter news, a Variable Font version of Source Han Serif—or Source Han Sans—would be a single font resource that should be approximately 30% the size of the Super OTC.
