### ISSUE TITLE
The subset JP font seems not have the word 鄉

### ISSUE THREAD

**Issue by tasty0tomato** [adobe-fonts/source-han-serif#179]
### Prerequisites

* [ ] If you are reporting an issue that affects glyphs for characters for a particular region or regions, did you verify that the characters are within the supported scope of the region or regions? This generally means GB 18030 or Tōngyòng Guīfàn Hànzìbiǎo (通用规范汉字表) for China, Big Five or CNS 11643 Planes 1 & 2 for Taiwan, HKSCS-2016 for Hong Kong, the JIS standards for Japan, and KS X 1001 and KS X 1002 for Korea.
* [x] Did you thoroughly search the [open](https://github.com/adobe-fonts/source-han-serif/issues) and [closed](https://github.com/adobe-fonts/source-han-serif/issues?q=is%3Aissue+is%3Aclosed) issues to avoid reporting a duplicate issue?
* [x] Did you go through the [official font readme file](https://github.com/adobe-fonts/source-han-serif/raw/release/SourceHanSerifReadMe.pdf) to better understand the scope of the project, to include the *Known Issues* section at the very end?

### Description

Sorry about not being able to check the first prerequisite.
The subset JP font seems not have the word 鄉
![ApplicationFrameHost_53h2VTM1U4](https://user-images.githubusercontent.com/48764449/223328482-2f0c7f8c-81c5-4026-8417-16486d1e3883.png)

**Comment by Marcus98T** [comment]
This character, 鄉 (U+9109, Chinese form), is not part of Adobe-Japan1 and therefore it is not included in the JP subset. You might be looking for 郷 (U+90F7, shinjitai form) or 鄕 (U+9115, kyujitai form) instead, both of which are encoded. Unfortunately, due to Unicode's Source Separation Rule, these three characters with the same meaning are encoded separately, which is off-scope with regards to this Adobe project. Further details [here](https://en.wikipedia.org/wiki/Han_unification) (or you can find the Chinese version in the languages section and read from there), which is complicated to understand.

Consider this issue closed because this is working as intended.

**Comment by tasty0tomato** [comment]
Thank you very much. Sorry about not knowing these differences
