### ISSUE TITLE
Minor stroke issue with 孓 (U+5B53), ExtraLight master only

### ISSUE THREAD

**Issue by Marcus98T** [adobe-fonts/source-han-serif#187]
The ending connecting stroke in the middle of the 了 part looks to be a bit too thin, as circled.

<img width="488" alt="Screenshot 2023-05-30 at 15 17 27" src="https://github.com/adobe-fonts/source-han-serif/assets/10541683/578f9e7c-94a6-4647-80c2-e16209301b41">

So checking in Glyphs, it looks like it's in the wrong place compared to 子 (U+5B50). Please fix, by moving the top of the second stroke of 了 a bit lower, and maybe shifting the ending connecting stroke a bit to the left. I might see how it is done later.

<img width="691" alt="Screenshot 2023-05-30 at 15 11 31" src="https://github.com/adobe-fonts/source-han-serif/assets/10541683/ed79da2c-aaad-483e-9211-0058208c1dfb">

The fix should basically reference the shape of 子 (U+5B50):

<img width="680" alt="Screenshot 2023-05-30 at 15 13 16" src="https://github.com/adobe-fonts/source-han-serif/assets/10541683/5d885e55-0e31-445c-bbda-704177c0ea59">

---

**UPDATE:** Also please adjust the last throw stroke in 孓 for balance and symmetry. Move the upper left end until it's symmetrized with the lower right end.

**Comment by Marcus98T** [comment]
In addition to the last throw stroke balance adjustment I just edited into my original post, the position of the 了 part is a bit too high compared to the other 了/子 components. It should be levelled out to make it more consistent. Heavy weight is also affected, although the middle connecting part should be fine.

<img width="478" alt="Screenshot 2023-05-31 at 16 55 03" src="https://github.com/adobe-fonts/source-han-serif/assets/10541683/db6164d1-a6f5-4183-bc87-5170969c0087">

**Comment by CoolMarvel43** [comment]
Fix has been verified. While still not perfect, it looks more balanced.

<img width="441" alt="Screenshot 2024-07-31 at 22 34 12" src="https://github.com/user-attachments/assets/3c163849-bfeb-455a-b47f-55a1905621e7">

I would have personally preferred if the last throw stroke would have been more symmetrical (similar to LiSong Pro, marked in green), but anyway the adjusted character does follow other Simplified Chinese typefaces with this kind of slight asymmetrical balance, so I guess this issue is resolved for now.

<img width="642" alt="Screenshot 2024-07-31 at 22 45 26" src="https://github.com/user-attachments/assets/eb291ddf-e6bf-4e37-9967-a272facf7739">
