### ISSUE TITLE
莁(U+8381) and 菄(U+83C4) has wrong radical 艹 for CN

### ISSUE THREAD

**Issue by CrotchBurnt** [adobe-fonts/source-han-serif#200]
![image](https://github.com/adobe-fonts/source-han-serif/assets/6418433/dfa7da4a-acc5-487a-ae09-68c65f4fd023)

**Comment by Marcus98T** [comment]
A [similar issue](https://github.com/adobe-fonts/source-han-sans/issues/313) has been reported for Sans in 2021.

Unfortunately due to limited glyph space, [some CN glyphs will show JP or TW/HK forms](https://github.com/adobe-fonts/source-han-sans/issues/412) as the only glyph shape for CN, although most of them are rare-use characters which may not reflect actual usage in China. Most of those affected glyphs are GB Extension characters, although some of them, in the case of showing TW/HK forms, are G3 or G5 characters according to the Unicode charts.

When I'm free, I will list down all the CN glyphs showing JP forms and TW/HK forms for Serif in a separate issue.

**Comment by punchcutter** [comment]
These glyphs only have a TW form right now and no current plan to add a CN glyph without some compelling argument.

**Comment by Marcus98T** [comment]
> and no current plan to add a CN glyph without some compelling argument.

@punchcutter I see.

Which is why I suggest that the Sans and Serif readmes should [add a note that not all GB 18030 characters are CN-compliant](https://github.com/adobe-fonts/source-han-sans/issues/412). That way people at least can know that Adobe is aware of this issue and may probably address it with a major redesign, or will not be addressing it due to technical limitations.

Sorry to bring it up again and again.
