### ISSUE TITLE
Outline issue with uni5A1B-CN (娛) (Heavy master only)

### ISSUE THREAD

**Issue by Marcus98T** [adobe-fonts/source-han-serif#208]
The two parts in the 吳 component seem to have minor gaps as circled in the picture. Please fix.

<img width="319" alt="Screenshot 2024-01-12 at 17 08 34" src="https://github.com/adobe-fonts/source-han-serif/assets/10541683/94b78f07-7824-4497-abe2-223a8c77e6b3">

<img width="755" alt="Screenshot 2024-01-12 at 17 07 15" src="https://github.com/adobe-fonts/source-han-serif/assets/10541683/28705db0-82c2-4d40-abfa-b7179b279238">

**Comment by CoolMarvel43** [comment]
Fix verified. This issue is considered resolved.

<img width="690" alt="Screenshot 2024-07-31 at 22 52 10" src="https://github.com/user-attachments/assets/b614fb20-9609-4773-bdc0-6abce7281452">
<img width="986" alt="Screenshot 2024-07-31 at 22 52 25" src="https://github.com/user-attachments/assets/d24c49c5-019a-4da3-941d-814b9795cf34">
(Closeup of the character with the problematic areas fixed)
