### ISSUE TITLE
Nominal form of U+1178 ᅸ, nominal form & vjmo01 glyph of U+D7B5 ힵ

### ISSUE THREAD

**Issue by acuteaccent** [adobe-fonts/source-han-serif#25]
1. The nominal form of U+1178 ᅸ is wrong. U+1178 is ㅑ + ㅗ, not ㅑ + ㅛ (ㅑ + ㅛ is U+1179 ᅹ).
2. The nominal form and the vjmo01 glyph of U+D7B5 ힵ are wrong. U+D7B5 is ㅜ + ㅕ, not ㅗ + ㅕ (ㅗ +ㅕ is U+D7B0 ힰ).

**Comment by kenlunde** [comment]
Thank you. The following three glyphs need adjustment: _uni1178_, _uniD7B5_, and _uniD7B5.vjmo01_.

**Comment by kenlunde** [comment]
I received the fixed glyphs from Sandoll's designer, which are shown below in the ExtraLight, Medium, and heavy weights. The mappings from the backend CIDs to the glyph names are below:

`CID+121 = uni1178`
`CID+446 = uniD7B5`
`CID+12563 = uniD7B5.vjmo01`

![shserif-issue-25-fix](https://cloud.githubusercontent.com/assets/3988788/24869208/565f2bba-1dc7-11e7-81f7-86ae491bf5fd.jpg)

Note that _uniD7B5.vjmo01_ is shown before it is shifted to the left and its horizontal advance is zeroed out (this is to be able to see the fix more clearly, because it would otherwise display over the glyph for _uniD7B5_).

**Comment by acuteaccent** [comment]
Awesome.

**Comment by acuteaccent** [comment]
BTW, I checked all the glyphs of conjoining hangul jamo (nominal forms, ljmo0[1-6], vjmo0[1-2], and tjmo0[1-4]; haven't checked the high-frequency 500 archaic hangul syllables) in Source Han Serif. I found no other errors besides the ones I have reported so far.

**Comment by kenlunde** [comment]
Thank you for the positive report. Also, thank you for checking these glyphs and reporting the issues that resulted in 22 glyph corrections. The fixes will be reflected in the first dot-release.

**Comment by kenlunde** [comment]
Consolidated with Issue #27.
