### ISSUE TITLE
Incorrect glyph for 壳(U+58F3) in TC version

### ISSUE THREAD

**Issue by extc** [adobe-fonts/source-han-serif#26]
Take a look at the reference font provided by Taiwan MOE website, U+58F3 is 士冖一几,
while U+58F3 in 思源宋體 is 土冖几. 
<img width="567" alt="un" src="https://cloud.githubusercontent.com/assets/8214015/24830924/a14dd470-1cc1-11e7-95ad-3b85b3fca92b.PNG">

There is a glyph already created in the OTF file,
just next to the glyph that the font currently using.
![sourcehanseriftc-bold](https://cloud.githubusercontent.com/assets/8214015/24830909/5a28d270-1cc1-11e7-8ae7-e5159b8f950a.jpeg)

**Comment by kenlunde** [comment]
Thank you for this report.

Please note that U+58F3 is outside the claimed support for Traditional Chinese, mainly because it is in CNS 11643 Plane 3.

However, because an existing glyph can be repurposed, _uni58F3-JP_, it is a relatively easy adjustment to the TW CMap resource, and will be considered an enhancement, not a genuine bug.

**Comment by kenlunde** [comment]
Consolidated with Issue #27.
