### ISSUE TITLE
Upload font files in separate archive files (.zip/.7z) into Github's release page

### ISSUE THREAD

**Issue by be5invis** [adobe-fonts/source-han-serif#3]

**Comment by ShikiSuen** [comment]
They are not likely to listen. Ken Lunde already knew I did this on my mirrored SHSans download on CodePlex (now Nuked). If they really wont to do this, it should already be done with their SHSans repo here.

Plus, 7z is not natively supported by macOS. I suggest using tar.gz if it has better compression rate than zip.

**Comment by be5invis** [comment]
@ShikiSuen `7z` is not supported natively on any platform but it performs better compression rate.

**Comment by Pal3love** [comment]
I don't think 7z would be considered because decompressing zip is easiest on any platform than any other formats, and just as you mentioned, 7z isn't natively supported.

**Comment by ShikiSuen** [comment]
@be5invis Maybe Microsoft Windows will support it (plus commandline operation for 7z format).

**Comment by kenlunde** [comment]
Using a compression format other than ZIP is a nonstarter. The "release" branch includes on its landing page convenient download links for pre-prepared ZIP files that group related fonts by language or weight. In some cases, multiple ZIP files were necessary due to GitHub's 100MB file size limit. The Super OTC was necessarily provided as a two-part split ZIP file.

**Comment by ShikiSuen** [comment]
@be5invis 這「Release **Branch**」可以直接用 curl 下載零散的檔案（而非在 Release 頁面）：
https://github.com/adobe-fonts/source-han-serif/tree/release
