### ISSUE TITLE
Missing CID glyphs from region-specific subset OTFs

### ISSUE THREAD

**Issue by hfhchan** [adobe-fonts/source-han-serif#31]
I have discovered some CID glyphs are not present in any Region-specific Subset OTFs but show up when using JP/KR's language-specific OTFs.  They also show up using CN/TW's language-specific OTFs when the language is set back to JP/KR.

An excerpt of CIDs are here:
2444
2483
2488
2492
15087
26366
26471
27595
45811

The involved CID glyphs I have found so far satisfy all of the following criteria:
- does not appear in any Region-specific subset OTFs
- used by default by the JP Language-specific Subset OTFs
- used by default by the KR Language-specific Subset OTFs
- not used by default by the CN Language-specific Subset OTFs
- not used by default by the TW Language-specific Subset OTFs

Any CIDs that are shared across the CN/TW & JP/KR boundary do not exhibit this issue.

**Comment by jimmymasaru** [comment]
And these glyphs don't exist in SHSans. I guess they are either KR Hanja for personal names or will be included in future versions of AdobeJapan1.

**Comment by hfhchan** [comment]
They are marked as -JP in https://raw.githubusercontent.com/adobe-fonts/source-han-serif/release/Resources/AI0-SourceHanSerif though...

**Comment by hfhchan** [comment]
Interestingly, similar effect can be seen with Source Han Sans, but with different CID numbers.

**Comment by kenlunde** [comment]
As stated in the ReadMe (PDF) of both _Source Han_ families (see the table in the "Glyph Set & Region-specific Subsets" section on page 6) the region-specific subset OTFs for Japanese include only the ideographs for Adobe-Japan1-6, along with a very small number of additional ideographs because they are part of the common subset definition. The additional JP ideographs are those designed by Iwata. This is more noticeable in _Source Han Serif_ because it includes over three times more Iwata-designed ideographs.

**Comment by hfhchan** [comment]
Hmm that means that the region-specific subsets combined have less region-specific coverage than any language-specific OTF?

This indeed seems implied albeit very indirectly upon reading of the related sections.

👌

**Comment by kenlunde** [comment]
If it were up to me, we wouldn't even build the region-specific subset OTFs, because they defeat the purpose of a Pan-CJK typeface. 😉
