### ISSUE TITLE
U+74E6 lookup error with JP language font and zh-TW locale

### ISSUE THREAD

**Issue by hfhchan** [adobe-fonts/source-han-serif#43]
![image](https://cloud.githubusercontent.com/assets/8191296/25064861/69382aac-2236-11e7-99c1-2dc1510cc82e.png)

For some reason, when specifying zh-TW and Source Han Serif (the Japanese language-specific version), 27527 is not substituted with 27526.  However, when the language is set to zh-HK, there is no problem.

The error does not occur in Source Han Serif TW (the Taiwanese regional-specific subset version).

Demo: https://codepen.io/anon/pen/Emjaxq

**Comment by hfhchan** [comment]
The issue is caused in `Regular/OTC/features.OTC.J`
Under `lookup jp2tw useExtension {`
`substitute \27526 by \27527;`
which is incorrect.

Meanwhile, in `UniSourceHanSerifTW-UTF32-H`,
`<000074e5> <000074e6> 27525`
which is correct.

**Comment by hfhchan** [comment]
In `Regular/OTC/features.OTC.SC`
Under `lookup cn2tw useExtension {`
`substitute \27527 by \27526;`
which is correct.

In `Regular/OTC/features.OTC.K`
Under `lookup kr2tw useExtension {`
`substitute \27526 by \27527;`
which is incorrect.

**Comment by kenlunde** [comment]
Thank you for reporting this.

Whew! I was worried that my script for generating the lookups for the 'locl' GSUB feature had a bug. The bug is elsewhere, and the fix is to map a completely different code point to the correct glyph.

U+74E6 瓦 correctly maps to _uni74E6-JP_ in the TW CMap resource, but U+2F61 ⽡ maps to _uni74E6-CN_, but should instead map to _uni74E6-JP_. I am closing this and consolidating with Issue #37.
