### ISSUE TITLE
Incorrect width for character 关 on Serif K

### ISSUE THREAD

**Issue by PhantomThief** [adobe-fonts/source-han-serif#5]
compare to Source Han Sans
the character 关 has larger width on Source Han Sans K to Source Han Sans
while, it has wrong width for Serif K comparing to Serif.

<img width="191" alt="screen shot 2017-04-04 at 4 53 56 pm" src="https://cloud.githubusercontent.com/assets/1650427/24648863/a2399cec-1957-11e7-8860-91f145998a20.png">

**Comment by jimmymasaru** [comment]
+1 for this issue because:
1. 关 is not used in South Korea so that it doesn't matter which one is used.
2. It can benefit those Chinese users who also prefer Kangxi Style glyphs because Korean variant is the closest one to Kangxi Style. It could make glyphs more consistent (at least widthwise) since this character is quite commonly used.
Moreover, 复 has the same situation.

**Comment by kenlunde** [comment]
@jimmymasaru is correct that U+5173 关 doesn't correspond to either KS standard, so while I consider this a bug, it is not considered urgent. We did override its glyph for the KR fonts of _Source Han Sans_ to use the CN glyph, _uni5173-CN_, and that override fell between the proverbial cracks. I made a note to add the override for the first update. It is a simple fix, but because it is not urgent for reasons already explained, it will not trigger an update.

Thank you for noticing and reporting this.

**Comment by ShikiSuen** [comment]
Will this also be applied for the next release of SHSans?

**Comment by ShikiSuen** [comment]
Oh I just noticed that it is applied. Sorry for my mistake.

**Comment by kenlunde** [comment]
Right.

**Comment by KrasnayaPloshchad** [comment]
The following material can be sen as model:
http://old.pep.com.cn/lsysh/jszx/tbjxzy/tpsc/photo/f/201008/t20100827_800362.htm

**Comment by kenlunde** [comment]
Consolidated with Issue #27.

**Comment by KrasnayaPloshchad** [comment]
>The following material can be seen as model:
>http://old.pep.com.cn/lsysh/jszx/tbjxzy/tpsc/photo/f/201008/t20100827_800362.htm

Also see: https://tinyurl.com/k2hzug8

**Comment by kenlunde** [comment]
The situation for U+5173 关 is no different than _Source Han Sans_. I simply forgot to override the mapping for the KR CMap resource like I did for that typeface. The JP is form is unique in that it is thinner. The form used by CN and TW should not be thin, and although this character is outside the scope of the KR support, meaning not in KS X 1001 or KS X 1002, it is an easy fix.
