### ISSUE TITLE
Why `Source Han Serif`, not `Source Han Serif J`?

### ISSUE THREAD

**Issue by OwenChia** [adobe-fonts/source-han-serif#50]
There are `Source Han Serif K` for Korean, `Soure Han Serif SC` for Simplified Chinese, `Sourcce Han Serif TC` for Traditional Chinese,
but why Japanese version called `Source Han Serif`, not `Source Han Serif J`?
![spectacle mn7431](https://cloud.githubusercontent.com/assets/2796153/25466379/f02dd96e-2b3a-11e7-9bc4-8b58b41cdd70.png)

**Comment by kenlunde** [comment]
When we first released _Source Han Sans_, we released only a single set of language-specific OTFs (with a Japanese default and with no language identifier), in addition to OTCs that supported all four languages. The idea was that the language-specific OTFs could use the 'locl' GSUB feature to access the glyphs for the other languages, and that users that didn't use environments that supported language-tagging could use the OTCs. That sort of fizzled out, so we ended up deploying separate language-specific OTFs as part of the Version 1.001 update.

Background: in order to make the original Japanese-default OTFs cleaner, in terms of their default names, we chose to not include a language identifier. We actively try to avoid changing font names, which is why _Source Han Sans_ still does this, and for parity with _Source Han Serif_, I chose to continue this.
