### ISSUE TITLE
Design difference between Source Han Sans SC and Source Han Serif SC

### ISSUE THREAD

**Issue by dadasutasudadas** [adobe-fonts/source-han-serif#55]
Four characters were found in Source Han Serif SC that have different design with Source Han Sans SC.
 They are 䙛(U+465B),⻞(U+2EDE),㨗(U+3A17),渉(U+6E09).
![170504_4glyphsquestion](https://cloud.githubusercontent.com/assets/21096794/25695936/11ce5368-30f0-11e7-9bfe-837b5d0b0cf3.JPG)

**Comment by kenlunde** [comment]
For U+565B 噛, this is a known (by me) issue for the CN glyph of [_Source Han Sans_](https://github.com/adobe-fonts/source-han-sans/), and is targeted to be fixed in Version 2.000 by adding a new CN glyph, _uni565B-CN_.

For U+2EDE, we did something special for _Source Han Sans_, specifically that we created a CN glyph for U+2967F 𩙿, _u2967F-CN_, then mapped U+2EDE to it in the CN and, by extension, TW CMap resources. We'll need to do the same for _Source Han Serif_.

U+3A17 㨗 requires a new CN glyph, _uni3A17-CN_, to be added. The sole glyph for this character is a JP one.

U+6E09 渉, both _Source Han_ families include a CN glyph, _uni6E09-CN_, and I'd argue that _Source Han Serif_ is correct, and that the _Source Han Sans_ glyph needs to be fixed.

I will consolidate this issue with the appropriate _Source Han Sans_ and _Source Han Serif_ issues later today, then close it.
