### ISSUE TITLE
Design difference between Source Han Sans SC and Source Han Serif SC 3

### ISSUE THREAD

**Issue by dadasutasudadas** [adobe-fonts/source-han-serif#57]
Three  characters were found in Source Han Serif SC that have different design with Source Han Sans SC.
They are U+3402 㐂, U+3455 㑕, U+3665 㙥
![design difference between source han sans sc and source han serif sc 3](https://cloud.githubusercontent.com/assets/21096794/25738339/77c20382-31b7-11e7-9562-dfcad8704e69.JPG)

**Comment by kenlunde** [comment]
For U+3402 㐂, _Source Han Serif_ requires a new CN glyph. For U+3455 㑕, it is a design difference. For U+3665 㙥, it is a known _Source Han Sans_ issue (_Source Han Serif_ is correct).

**Comment by hfhchan** [comment]
FYI, for 夕, it is the PRC norm for the dot to touch the bottom stroke in sans-serif, while the dot touches the first stroke in serif.

This is a well thought out design: in serif, if the dot is joined to the bottom stroke, since the dot is considerably thicker at the end, it would result in ink smearing.

In sans-serif, having the dot joined at the bottom instead of the top helps recreate the visual "water droplet" traditional aesthetic.

It is unfortunate that Taiwan and Hong Kong had not taken into account these techniques when designing the official glyph standards.
