### ISSUE TITLE
Design difference between Source Han Sans K and Source Han Serif K 2

### ISSUE THREAD

**Issue by dadasutasudadas** [adobe-fonts/source-han-serif#60]
I noticed 15 characters that differ in character form concerning KS X 1001 between Source han serif K and Source han sans K.
U+501C 倜, U+5192 冒, U+52C7 勇, U+5357 南, U+54E5 哥, U+553E 唾, U+5DFD 巽, U+641C 搜, U+68D7 棗, U+722C 爬, U+7A20 稠, U+7C3F 簿, U+8983 覃, U+8D16 贖, U+8F27 輧
![kr_diff2](https://cloud.githubusercontent.com/assets/21096794/26136189/7a3eb0a0-3af5-11e7-9336-78229a392091.JPG)

**Comment by kenlunde** [comment]
Here is a quick summary before I call it a night: 10 of these are handled by mapping to the CN glyph. One looks like a _Source Han Sans_ bug. One is a stylistic difference. One requires a new KR glyph. Two require a new JP glyph, which will be shared with KR.

**Comment by dadasutasudadas** [comment]
Thank you for the input. One more difference I found is U+73F9 珹. 
![kr_diff2-1](https://cloud.githubusercontent.com/assets/21096794/26144116/9e795c2c-3b22-11e7-91ee-0507fc23b264.JPG)

**Comment by kenlunde** [comment]
The mappings for U+501C 倜, U+5192 冒, U+52C7 勇, U+553E 唾, U+5DFD 巽, U+641C 搜, U+73F9 珹, U+7A20 稠, U+7C3F 簿, U+8983 覃, and U+8D16 贖 will be changed so that the respective CN glyphs are used in the KR CMap resource.

**Comment by kenlunde** [comment]
For U+54E5 哥 and U+68D7 棗, new JP glyphs, _uni54E5-JP_ (aka Adobe-Japan1-6 CID+4378) and _uni68D7-JP_ (aka Adobe-Japan1-6 CID+5224), respectively, will be added, which will also be used in the KR CMap resource.

For U+8F27 輧, a new KR glyph will be added, _uni8F27-KR. (For _Source Han Sans_, because the existing JP glyph corresponds to an Adobe-Japan1-6 kanji (CID+ 19874 ), the current JP glyph can become a new KR glyph, the JP glyph needs to be corrected, and the CN glyph can be removed).

For U+5357 南, the single _Source Han Sans_ glyph, _uni5357-CN_, looks wrong. I recorded this for the Version 2.000 update.

U+722C 爬 looks like a style difference.
