### ISSUE TITLE
Fullwidth Parenthesis after Fullwidth Latin character in vertical writing displayed in horizontal form

### ISSUE THREAD

**Issue by bobbytung** [adobe-fonts/source-han-serif#62]
It's an interesting issue.

I use Source Han Serif (TW subset) as embedded font to try typography for Google Play Books. Every Full width parenthesis (i.e. [（] U+FF08、[）] U+FF09) that after Fullwidth latin character in vertical writing will fallback to horizontal form. 

[sample 1](https://goo.gl/photos/otNwbtS4gtM2HEYM8) : Line 2 [（] after NGO
[sample 2](https://goo.gl/photos/bF2SPX5wiqhRZT8D6) : Line 3 [）] after NLD

It might be Google Play Book's issue. But it works fine with Source Han Sans (system font in Android 7).

**Comment by kenlunde** [comment]
Given that the issue appears in particular contexts, and given that the affected glyphs are not covered by any of the contextual OpenType features, it is most definitely a Google Play Book issue. This issue seems related to text runs and how HarfBuzz (cc @behdad) performs certain optimizations on all of the glyphs for a particular text run, which is likely preventing the 'vert' GSUB feature from being applied. The full-width parentheses are likely part of the text run that includes the full-width Latin.

The different behavior between _Source Han Sans_ and _Source Han Serif_ is likely due to other reasons, perhaps a bit of hard-wiring on the part of Google.

**Comment by behdad** [comment]
Yes that sounds like itemization issue, specific to certain implementations, not the font.
