### ISSUE TITLE
True italics?

### ISSUE THREAD

**Issue by be5invis** [adobe-fonts/source-han-serif#75]
I know you have already run out of CIDs, but could we provide a true italics?
Replacing all Latin glyphs to their italic form, while everything else is not changed (or slanted if necessary).

**Comment by Explorer09** [comment]
Why are you bothered to include italics in Source Han when there are Source Sans Pro / Source Serif Pro italic already?
If we want Han "italic" font, it would better be a _damn_ italic font with all Han glyphs in regular script (kaishu) style. But that definitely won't happen soon.

**Comment by kenlunde** [comment]
The ideal way to include _italic_ glyphs in an East Asian font, whose Western glyphs represent a tiny minority, is to simply add them to the glyph set, such as what was done in Adobe-Japan1-4 and higher Supplements. The _italic_ glyphs are accessible via the '[ital](https://www.microsoft.com/typography/otspec/features_fj.htm#ital)' (_Italic_) GSUB feature, though I plan to rebuild the _Kozuka_ families to include an _Italic_ face, then deploy them as OpenType Collections whose faces share the same CFF. Our latest commercial Japanese font, [_Ten Mincho_ (貂明朝)](https://blogs.adobe.com/CCJKType/2017/11/ten-mincho.html), does precisely this, too, by adding a very rich set of Latin glyphs, to include a full set of corresponding italic glyphs, all in a shared glyph set that will soon be deployed as an OpenType Collection.

However, to produce a parallel glyph set that differs only in that the Western glyphs are italic is considered _wagging a huge dog by a tiny tail_, and therefore a non-starter. Also, [_Source Serif Pro_](https://github.com/adobe-fonts/source-serif-pro) does not yet have an _Italic_ face. I would very much like to add the _italic_ glyphs, but as we have run out of CIDs, and because proper HK support (that is being worked on) has a much higher priority, it is not likely to happen in the near future.

**Comment by kenlunde** [comment]
There are plenty of use cases that involve _italic_ glyphs for the Western characters in CJK fonts, such as emphasizing a Western word or phrase, or properly referencing a book title. Also, the Western glyphs that are included in a CJK font are often [scaled or adjusted](https://blogs.adobe.com/CCJKType/2015/01/shs-vs-ssp-and-scp.html) in order to work better with the CJK glyphs, meaning that using a separate _Italic_ face that corresponds to the upright glyphs that are included in the CJK font may not produce consistent results. Of course, there are ways to make such adjustments, such as through the use of CFR (_Composite Font Representation_ or [ISO/IEC 14496-28](http://standards.iso.org/ittf/PubliclyAvailableStandards/)) objects, but they are not widely supported.

**Comment by KrasnayaPloshchad** [comment]
> The italic glyphs are accessible via the 'ital' (Italic) GSUB feature, though I plan to rebuild the Kozuka families to include an Italic face, then deploy them as OpenType Collections whose faces share the same CFF. 

You can also try `ital` axis in variable fonts.
