### ISSUE TITLE
Name of Source Han Serif TW

### ISSUE THREAD

**Issue by groverlynn** [adobe-fonts/source-han-serif#8]
Names of different weight of Source Han Serif TW are not consistent. When I install them in Mac, most of them go under the font family "Source Han Serif TW", while "Regular" and "Bold" go under the font family "思源宋體 TW". Hence, the latter two weights are in a different font family than other weights.
Moreover, it should be called "思源**明**體 TW" instead.

**Comment by zerng07** [comment]
"A serif-style CJK font goes by many names: Song (宋体) in Mainland China, Ming (明體) in Hong Kong, Macao and Taiwan, Minchō (明朝) in Japan, and Myeongjo (명조) or Batang (바탕) in Korea. The names and writing styles originated during the Song and Ming dynasties in China, when China's wood-block printing technique became popular. " quote from Google Developer Blog: https://developers.googleblog.com/2017/04/noto-serif-cjk-is-here.html

Actually most people in Taiwan refer it as 明體 while some of us use 宋體 as the name. This is due to the most used Serif Chinese font in Taiwan are "細明體" and "新細明體" by Microsoft. However, the term "宋體" is adopted by Ministry of Education in "國字宋體母稿" while most of the popular Serif style Chinese font produsts published by the vendors use "明體" for traditional Chinese products and "宋體" for simplified Chinese products.

**Comment by zerng07** [comment]
In my opinion, using "明體" as the name is a good idea to make more people in Taiwan and Hong Kong more familiar. It is more localized and better fit the actual naming situation in those regions.
Although 宋體 is still accepted after all, it might bring some confusions for general public who don't know the history well.

**Comment by kenlunde** [comment]
@groverlynn: With regard to the issue described in your first paragraph, this is a known macOS issue in how it deals with the localized strings in the 'name' table. _Source Han Serif_, unlike _Source Han Sans_, lacks Macintosh 'name' table strings, and this exposed a minor bug in how macOS enumerates fonts. This issue is explicitly mentioned in the _Known Issues_ section of the official ReadMe file (see page 23). The next major macOS update (Version 10.13?) is expected to fix this. This issue was already reported to our friends at Apple.

**Comment by ShikiSuen** [comment]
@zerng07 Using 宋體 for this typeface is academically not tolerable because what people said 仿宋 is actually the real 宋體. I would like to wait and see Ken's further explanations regarding their current choice of translation. I see this as a great opportunity to let us Mainland Chinese users know the correct academic term for Chinese Serif fonts.

**Comment by kenlunde** [comment]
Although originally reported in Issue #1, I am replying to the Traditional Chinese font-naming issue in this issue due to corruption of that issue's history.

The use of 宋體 in the Traditional Chinese name is both intentional and appropriate if you consider the scope of the entire typeface. I agree that for a completely stand-alone typeface, it would not be appropriate. The only _Source Han Serif_ fonts for which it could be considered to use 明體 instead are the region-specific subset OTFs for Traditional Chinese, because they behave as conventional Traditional Chinese fonts whose scope of CJK Unified Ideograph coverage is aligned to Big Five. For the sake of consistency with the rest of the typeface, the use of 明體 in the names of the region-specific subset OTFs for Traditional Chinese will not happen.

(If it were up to me, the region-specific subset OTFs would not exist, because I find them to be uninteresting due to the fact that they are not Pan-CJK fonts, which is the whole purpose of this typeface design.)

In terms of appropriateness, the Taiwan MOE standard itself uses 宋體 in its title, which was already mentioned by @zerng07. I just scanned the cover of my copy:

![moe](https://cloud.githubusercontent.com/assets/3988788/24669339/e1136dfa-191e-11e7-9a36-f2764bfe5fc7.jpg)

Also—and perhaps more importantly—any character that is outside the scope of Big Five is not guaranteed to render in a way that is suitable for Traditional Chinese use, and based on how the mappings work, most characters are likely to display using a Simplified Chinese glyph, some of which happen to be appropriate for Traditional Chinese use. In addition, in a Pan-CJK context, using 宋体 for Simplified Chinese and 宋體 for Traditional Chinese provides naming consistency, and the 體 in 宋體 should make it clear (or clearer) that the font is intended for Traditional Chinese, not Simplified Chinese.

Of course, anyone who is genuinely bothered by this naming issue is free to fork the master branch of this project, then modify the _FontMenuNameDB_ and _FontMenuNameDB.SUBSET_ files to reflect 明體 instead of 宋體 by changing all instances of `\5B8B\9AD4` to `\660E\9AD4`, then rebuild. Other tools, such as ttx, can also be used to change the strings in the 'name' table of the ready-to-install font resources in the release branch.

**Comment by ShikiSuen** [comment]
One more time failed on wrong term chosen by the education bureaus in both markets. I feel so regretful for this time your team choose to dogeza to this without respecting the development of engraved font styles. (Though the last time it is nothing wrong to keep the MOE glyph branch of Source Hans Sans.)

**Comment by KrasnayaPloshchad** [comment]
Accoring to DynaComware, 宋體 and 明體 are different typefaces, here is a resource we can see their samples.
http://www.dynacw.com.tw/support/support_download_list.aspx?sid=6

**Comment by ShikiSuen** [comment]
@KrasnayaPloshchad The name of these font products among the two brochures are randomly named as 宋體 or 明體, except those typefaces made for Mainland PRC market. Note that 儷宋 and 儷黑 belong to 儷 family, which was initially purchased from a HongKong designer called 柯熾堅. Only 柯熾堅 could tell why 儷宋 is not named as 儷明.

**Comment by ShikiSuen** [comment]
/ Continued /
A typical example is: "DFPSongW*T-GB", "DFPSongW*-GB5", "DFPSongW*-GB" and "DFMing Std W*" are exactly under the same font family. They are just different glyph-standard branches of a same font. The reason why some of them are named as 宋體 is based on unnecessary respect to wrong practices in the Mainland PRC market.

![image](https://cloud.githubusercontent.com/assets/3164826/24735332/a278f80e-1a3f-11e7-946f-96401907bc6b.png)
![image](https://cloud.githubusercontent.com/assets/3164826/24735339/acc6351a-1a3f-11e7-93dc-2b2d73e3379e.png)
![image](https://cloud.githubusercontent.com/assets/3164826/24735352/bb8fac34-1a3f-11e7-9d1c-7619295c0fcc.png)
![image](https://cloud.githubusercontent.com/assets/3164826/24735380/e86f6b4a-1a3f-11e7-9f67-3de6adfdb7d9.png)

**Comment by hfhchan** [comment]
@shikisuen Your evidence illustrates perfectly how 華康 names the typeface as 宋 or 明 perfectly on the orthography used.

**Comment by ShikiSuen** [comment]
@hfhchan I treat this time a good chance to correct the orthography of the fontstyle name in Mainland China. According to @kenlunde:
![image](https://cloud.githubusercontent.com/assets/3164826/24758665/467b7228-1aa0-11e7-9e2f-ba93074d043f.png)
It is a great PITA not using this chance to uinify how this fontstyle should be called in the whole east asia to the historically correct one.

**Comment by justinrleung** [comment]
FWIW, on the CNS11643 Master Ideographs Seeker (全字庫) website, they do list both 宋體 and 明體 (although I don't really see a difference other than the resolution). Take a look at the [page for 體](http://cns11643.gov.tw/AIDB/query_general_view.do?page=1&code=7c55).

@ShikiSuen I don't think it's appropriate to unify East Asia with one name simply because it is historically accurate. I'm not saying that 宋體 is necessarily correct, but it has definitely caught on, especially in mainland China. Language changes, and there is 約定俗成. If we have to stick to what is historically accurate, we would have to be writing in the oracle bone script. (Maybe that's too far...) Since the scope of this font is the national standards, I think it is entirely appropriate to follow the names that are used by the standards, i.e. 宋體/宋体 for all three Chinese regions.

**Comment by ShikiSuen** [comment]
@justinrleung Let 約定俗成 go die if it always consists of illogical manners.

**Comment by justinrleung** [comment]
@ShikiSuen Then you are wishing death on language, which is largely a product of 約定俗成. Why do we write 愛 as 愛 instead of the more logical 㤅? Mostly because of 約定俗成. To some extent it is due to standards, especially in East Asian languages, but the standards must also consider what is 約定俗成.

**Comment by kenlunde** [comment]
Please keep in mind that GitHub issues are not a general discussion forum.
