### ISSUE TITLE
Source Han + MSOffice 2019 = … no pan-CJK?

### ISSUE THREAD

**Issue by JPRidgeway** [adobe-fonts/source-han-serif#81]
### Prerequisites

* [✓] If you are reporting an issue that affects glyphs for characters for a particular region or regions, did you verify that the characters are within the supported scope of the region or regions? This generally means GB 18030 or Tōngyòng Guīfàn Hànzìbiǎo (通用规范汉字表) for China, Big Five or CNS 11643 Planes 1 & 2 for Taiwan, HKSCS-2016 for Hong Kong (though support has been deferred until Version 2.000), the JIS standards for Japan, and KS X 1001 and KS X 1002 for Korea.
* [✓] Did you thoroughly search the [open](https://github.com/adobe-fonts/source-han-serif/issues) and [closed](https://github.com/adobe-fonts/source-han-serif/issues?q=is%3Aissue+is%3Aclosed) issues to avoid reporting a duplicate issue?
* [✓] Did you go through the [official font readme file](https://github.com/adobe-fonts/source-han-serif/raw/release/SourceHanSerifReadMe.pdf) to better understand the scope of the project, to include the *Known Issues* section at the very end?

Totally a not-this-product, but what is it to do with peculiar new behaviour since migrating from MS Office 2010 to 2019? Now it blankly refuses to use any glyphs but Japanese when typesetting in vertical. Noto versions also involved, no matter Serif, Sans, or Mono. After some trickery (which involved using only subset OTFs installed in a particular order) everything worked in 2010, but now no matter which version of fonts chosen, how they are installed, vertical typesetting=Japanese forms.

**Comment by kenlunde** [comment]
I made major improvements in terms of the declared _languagesystem_ scripts and languages in the _Source Han Sans Version_ 2.000 fonts, which are not yet reflected in the _Source Han Serif_ (Version 1.001) fonts, and which may affect behavior in MS apps. Please make sure that you're using Version 2.00x of the _Source Han Sans_ fonts. You should also visit the app settings and preferences. Global (OS-level) settings may also influence the behavior.

**Comment by JPRidgeway** [comment]
This is a sample from Source Han Sans, current version 2.001. Source Han Mono is same. I will 

![изображение](https://user-images.githubusercontent.com/9803610/58764673-dbafac80-8572-11e9-8f38-5dbad4d069ff.png)
![изображение](https://user-images.githubusercontent.com/9803610/58764676-e8cc9b80-8572-11e9-9fd2-c65fe2cf7bd4.png)

(Note version is 1803, I don't have access to 1903 now to try and reproduce)

**Comment by kenlunde** [comment]
Using the latest MS Word on macOS, the 'locl' GSUB feature is working as expected in vertical writing mode. If I enter 月曜日, select the text, select _Source Han Sans_ (Japanese) as the font, then change the specified language to something else, the correct glyph appears. For East Asian languages, the only choices for language tagging are Japanese, Korean, Chinese (China), and Chinese (Taiwan). Chinese for Hong Kong is not in the drop-down list. Of course, you're using Windows 10.

**Comment by tamcy** [comment]
Seems working fine in Word 2019 Version 1904 (build 11601.20230) on Windows 10. Here the TW font is used, with the text flagged as Japanese and Chinese (HK):

![shs-word2019-1904](https://user-images.githubusercontent.com/959433/58776477-7a80eb00-85fd-11e9-9a2b-e586ed891ec1.png)

![word2019ver](https://user-images.githubusercontent.com/959433/58776480-7c4aae80-85fd-11e9-9fdb-1251ca6de7d2.png)

**Comment by JPRidgeway** [comment]
Curiouser and curiouser. When horizontal (test on Super OTC of Sans), language-tagging does not change the outlook of the font. However, physical choice of another instance in the menu does. When vertical, tagging produces required result. However, physical choice fails. Only when doing BOTH the choice of particular instance and tagging as well, directions agree in doing their job.

**Comment by kenlunde** [comment]
@JPRidgeway I think that you've just met the "double-edge sword" that that is known as the 'locl' GSUB feature and language-tagging. For conventional CJK fonts that are designed to support a single language, language tagging has no effect, because such fonts lack the 'locl' GSUB feature.

In other words, for a Pan-CJK font that supports the 'locl' GSUB feature, and for which language tagging has an effect, it actually doesn't matter much which language you select, unless the app supports the notion of a default language (aka no language is selected). Adobe InDesign is such an app, but MS Word does not appear to be so. For example, if you select the font whose default language is Japanese, and if you want Japanese behavior, you either need to select no language (if possible) or select Japanese.

Based on the discussion thus far, I think that this issue can be safely closed. Feel free to continue discussion, or ask questions.

**Comment by tamcy** [comment]
I can confirm what @JPRidgeway said in my Word for Windows installation - language tagging works differently between horizontal and vertical modes. When writing horizontally, one has to select the font with default language to get the desired localized glyphs. Tagging the text with a different language has no effect. The opposite in vertical writing mode - one has to tag the text correctly to get the desired localized form. Choosing the font with a different default language has no effect.

**Comment by kenlunde** [comment]
**(Reminder To Self: Don't respond to GitHub issues until the morning coffee has been completely absorbed your system.)**

@JPRidgeway Congratulations, you seem to have discovered a genuine MS Word bug. I can confirm identical behavior in the macOS version of the app. I will be attending a one-week standardization meeting at Microsoft's HQ in Redmond starting two weeks from today, and will raise this bug with the appropriate folks there. (I will also bring up the lack of "Chinese (Hong Kong)" as a language choice.)

**Comment by kenlunde** [comment]
@JPRidgeway A friend at Microsoft provided a useful clue/tip. It seems that for the 'locl' GSUB feature to work, at least one other OpenType feature must be enabled. The reason why it works in vertical writing mode is because the 'vert' GSUB feature is automatically applied, satisfying that requirement. If you open the Format→Font… dialog, go to the Advanced tab, then enable "Use contextual alternates" (aka the 'calt' GSUB feature) then the 'locl' GSUB feature should start work in horizontal writing mode. I confirmed this in MS Word on macOS.

I think that this requirement should be lifted, because there are a non-zero number of use cases that involve only the 'locl' GSUB feature, as this issue clearly demonstrates.
