### ISSUE TITLE
Do you plan to launch italic and bold-italic fonts?

### ISSUE THREAD

**Issue by diguage** [adobe-fonts/source-han-serif#83]
Do you plan to launch italic and bold-italic fonts?

**Comment by frankrolf** [comment]
I think there wasn’t a plan to do this, since Italics are not very common in CJK typesetting.
If you are looking for Italic styles for non-ideographic writing systems, see here: https://github.com/adobe-fonts/source-serif-pro

**Comment by RuixiZhang42** [comment]
- Because every *Source Han* font has already run out of CIDs, it is technically impossible to include italic Latin/Cyrillic/Greek letters in the font file, and implemented them via the `ital` GSUB feature.
- Releasing a new set of separate fonts (say, *Source Han Serif ExtraLightItalic*, *Source Han Serif HeavyItalic*, etc.) seems to be a non-starter. The Ideograph/Kanji, Hangul, Katakana and Hiragana have no italic shape in East Asian writing systems. So you are looking at an “italic” font file containing 50,000+ glyphs that have no italic shape whatsoever while containing italic letters only around hundreds.

Please also check the already posted issue in this repository: https://github.com/adobe-fonts/source-han-serif/issues/75 and another one in https://github.com/adobe-fonts/source-han-sans/issues/191

So I think the short answer to your question is: No, there is no plan to to launch italic and bold-italic fonts in the *Source Han* projects.

**Comment by diguage** [comment]
@RuixiZhang42 @frankrolf 
Thank you very much. I'm sorry not to search it firstly.
