### ISSUE TITLE
New character

### ISSUE THREAD

**Issue by baiweiart** [adobe-fonts/source-han-serif#95]
Hello! I’m Baiwei - cryptoartist. In a recent project, I created a Chinese character for “NFT”. I used my sinological background and help from a famous Chinese font designer. Now I plan to add it to an open-source type file. I want the type to be available for everyone to use.

Having this new character created by a crypto artist and given to the community would be a very meaningful event in the crypto circle. Would you be interested in helping this to happen? 

![nft](https://user-images.githubusercontent.com/86760755/124065841-21007a00-da6a-11eb-8604-9512750f5d43.jpg)

**Comment by punchcutter** [comment]
This isn't really the place to ask. We would only consider adding a character like this if it is first accepted into Unicode.

**Comment by ruby3141** [comment]
"Making" Chinese character is a lot different than making a logo or artwork.
Yeah, you can make drawing LOOKS LIKE Chinese character and explain to others as your new symbol meaning NFT, but it is NOT Chinese character because Chinese people don't use it.
Chinese language is living language. Multiple billions of people are using it every day as there main means of communication.
You have to make some reasonable amount of Chinese people to use your symbol to make it "Chinese character".
Then Unicode will take consider of that character and add it, and THEN Adobe Source Han Serif will include the character.
